<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_shop Marketplace</name>
   <tag></tag>
   <elementGuidId>008121c5-80d5-4e71-a7e2-a43f85c95c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Marketplace']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Marketplace</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>377eed54-1f34-44d5-930b-62e626780708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator button-transition mat-button mat-button-base ng-star-inserted</value>
      <webElementGuid>5ab7134c-4cae-4eb8-b33a-4acb082f2b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Marketplace</value>
      <webElementGuid>b97cf2fa-a187-463a-a2d7-51a0cfa7bd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-14</value>
      <webElementGuid>bfd17c82-c5fe-4c96-874a-5e6c40c11ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shop Marketplace </value>
      <webElementGuid>99917ad3-252a-40cc-ab0c-5b41b0d15248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Marketplace&quot;)</value>
      <webElementGuid>fed28683-801e-42f3-a895-27791d2b7b54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Marketplace']</value>
      <webElementGuid>cc7fcd7b-0bf6-4ac6-8a22-3e74a642de2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Documents'])[1]/following::button[1]</value>
      <webElementGuid>f67ab428-ba32-47d5-800f-2e5b38995fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[1]/following::button[2]</value>
      <webElementGuid>b7b26cfe-597c-41db-8181-3f8f053d5fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::button[1]</value>
      <webElementGuid>595ca9d7-46b0-4f61-9465-3729048dd8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-menu-element[7]/button</value>
      <webElementGuid>acd43001-d21a-47b6-8ac2-c2ecfe013ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Marketplace' and (text() = 'shop Marketplace ' or . = 'shop Marketplace ')]</value>
      <webElementGuid>9f2b4c6d-9fa5-49bd-bc4b-0faeee921923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
