<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_content_paste Purchasing</name>
   <tag></tag>
   <elementGuidId>a92996b6-cd4a-4d75-a9cd-6e3f1751824b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Purchasing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Purchasing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03950ff9-88f6-451d-8231-6880367fa27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcbb2b44-ed1d-4f45-8d2c-ab3c0ff30e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger mat-button mat-button-base button-transition ng-star-inserted</value>
      <webElementGuid>b3b18b56-f251-4fd8-8e4b-c150ebc213b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Purchasing</value>
      <webElementGuid>47df8e5a-6497-4cd9-8aca-33c0ce6a89db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-11</value>
      <webElementGuid>b844d613-ec62-432e-b5ed-97f77e6aaa9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>content_paste Purchasing </value>
      <webElementGuid>f9245cf6-5c40-487e-8313-1c84cf7b7356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Purchasing&quot;)</value>
      <webElementGuid>619aff68-3ff1-4b2f-97e3-7361919dc8cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Purchasing']</value>
      <webElementGuid>b7e5e405-8bc2-494e-9a4e-ad944d996a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/following::button[1]</value>
      <webElementGuid>50cd3c70-df82-48da-9e4c-3cae89ddabfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warehouse'])[1]/following::button[2]</value>
      <webElementGuid>14fcf279-a918-4683-b7f9-d357189e891e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[1]/preceding::button[1]</value>
      <webElementGuid>9a4fc603-e4eb-4806-b97e-bedce1fe0b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-menu-element[4]/button</value>
      <webElementGuid>c55ff3a8-0db0-445b-bb84-48aab9640c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Purchasing' and (text() = 'content_paste Purchasing ' or . = 'content_paste Purchasing ')]</value>
      <webElementGuid>66d216e5-b451-42e0-addc-2c5e4fb2adbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
