<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_account_balance Accounting</name>
   <tag></tag>
   <elementGuidId>b836e902-e3e7-4595-a7ed-f23271dbbe99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Accounting']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Accounting</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>315c388a-20f3-4c03-b36b-5b9bf188d2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0837d5af-4870-4771-a70d-381b7fb3fafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger mat-button mat-button-base button-transition ng-star-inserted</value>
      <webElementGuid>c8f87133-2b22-435a-93b0-c88a41be4256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Accounting</value>
      <webElementGuid>6cd48e45-ced0-4735-a404-a852a61cb280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-12</value>
      <webElementGuid>7034cf6f-6422-4b2b-8c84-a0d86cf864e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>account_balance Accounting </value>
      <webElementGuid>6fd249e7-4a98-4542-82e6-fce13a74639e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Accounting&quot;)</value>
      <webElementGuid>d3c3d847-1aeb-408c-b32a-88660984e9f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Accounting']</value>
      <webElementGuid>d90925a6-b10a-4a4c-86f1-ca1346bcc485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchasing'])[1]/following::button[1]</value>
      <webElementGuid>c37c115f-a709-4805-8d99-f56db8e7c8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/following::button[2]</value>
      <webElementGuid>ca60beca-e114-4845-be37-5cc140e4e5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Documents'])[1]/preceding::button[1]</value>
      <webElementGuid>bc8c6893-5411-4ed3-b59f-4c403f42f93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-menu-element[5]/button</value>
      <webElementGuid>b9e6ef53-8489-413d-b19f-456f3c5e15bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Accounting' and (text() = 'account_balance Accounting ' or . = 'account_balance Accounting ')]</value>
      <webElementGuid>bae82246-9f1f-4689-aa4d-dc14c7c8ed3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
