<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_house Warehouse</name>
   <tag></tag>
   <elementGuidId>41479ca0-b98e-4aa4-822c-4068c30cd308</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Warehouse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Warehouse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b4ae2067-4e9e-4c9e-b4b4-f0bab8f39a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f10d15e5-b6c8-444d-b610-469b17853d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger mat-button mat-button-base button-transition ng-star-inserted</value>
      <webElementGuid>4eaedccc-0785-4df9-83c3-1cc9c63d7ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Warehouse</value>
      <webElementGuid>82f279e3-93a4-41a6-aa56-edb6f8f26eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>cdk-describedby-message-9</value>
      <webElementGuid>296e2191-0c8b-474f-adfd-2ac90ab47778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>house Warehouse </value>
      <webElementGuid>0d16ee7f-7332-484a-aaef-93ca62d25112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Warehouse&quot;)</value>
      <webElementGuid>7be32066-d5c1-4d52-a261-d4a9e74cf2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Warehouse']</value>
      <webElementGuid>740a5ae4-ae7d-4ffc-819c-c8b5dafc73e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::button[1]</value>
      <webElementGuid>2d303263-3a71-433c-8a63-b2b8a253c164</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/preceding::button[1]</value>
      <webElementGuid>2abecbb7-51f7-4e5c-bd48-5afca416f1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-menu-element[2]/button</value>
      <webElementGuid>fffd2f33-1570-4b14-a2ed-ce30074b6738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'Warehouse' and (text() = 'house Warehouse ' or . = 'house Warehouse ')]</value>
      <webElementGuid>3bae36ba-28b1-43d4-98d2-049040bcff07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
