<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sales_logo-transition ng-tns-c338-5</name>
   <tag></tag>
   <elementGuidId>2d4313d6-04d3-470c-bf19-cc73cb3181d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='logo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-transition.ng-tns-c338-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd0a5793-954c-469e-ae69-4ca72801d348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>05eb06df-e05e-44f3-9e18-2f56fc87facc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-transition ng-tns-c338-5</value>
      <webElementGuid>b83f34cc-889c-465e-8dd6-b702d83f2e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c514faa-3ffd-4aa3-b352-5b8c16a96486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/img/logo.png</value>
      <webElementGuid>79e3789b-ac0d-4181-9b2d-4feaeb04ab0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>nocollapse</value>
      <webElementGuid>edf41dd4-081f-4379-b44f-a6aaea7dd240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-oms-master[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-menu-display[@class=&quot;ng-tns-c338-5&quot;]/div[@class=&quot;ng-tns-c338-5 menu-transition ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c338-5&quot;]/img[@class=&quot;logo-transition ng-tns-c338-5&quot;]</value>
      <webElementGuid>713a5840-7a70-4c13-9764-fc99552619da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>a85f8339-6011-4f1c-9b38-ba3d49cada9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>a96328ee-f466-43a5-af2b-e9a68aee37b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo' and @src = './assets/img/logo.png']</value>
      <webElementGuid>0b6deffa-35fc-476a-b4c2-fb09d6eecb94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
