<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SME Hub Prieds_submit</name>
   <tag></tag>
   <elementGuidId>7409e11e-04f4-4406-9da6-ac26c7f9e9e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='homelandingpage-image-konsultasibisnis']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#homelandingpage-image-konsultasibisnis</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9614f884-21ee-47af-ad3f-04fea8e3ad2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>fe06d664-a23c-4e7c-a295-81e0409403cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>49f7cec2-c58a-4ed3-8b6e-f79eebc6978c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>09cedb39-e26f-42f2-935a-515bdfded383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-prieds ng-star-inserted</value>
      <webElementGuid>863e6099-b846-4c3f-b870-a0445b158357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>homelandingpage-image-konsultasibisnis</value>
      <webElementGuid>3508e7f6-1b51-4c54-9a0b-48ceb24cdd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://prototype-prieds-assets.s3.ap-southeast-1.amazonaws.com/PRIEDS/DOCUMENT/image-content4.png</value>
      <webElementGuid>7752f5ed-070a-464e-942e-37772959ea63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homelandingpage-image-konsultasibisnis&quot;)</value>
      <webElementGuid>0b34aa0a-8a9c-4243-b428-48b3f5f82267</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='homelandingpage-image-konsultasibisnis']</value>
      <webElementGuid>fbd2fbae-8d83-49c2-a526-dbe472b961e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a02d77ef-93d4-4482-ba8c-b066438f5a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'submit' and @alt = 'submit' and @id = 'homelandingpage-image-konsultasibisnis' and @src = 'https://prototype-prieds-assets.s3.ap-southeast-1.amazonaws.com/PRIEDS/DOCUMENT/image-content4.png']</value>
      <webElementGuid>33d0422f-d96c-4374-af2d-3a81ec0ba0d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
