<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>70477235-a8ef-4e7f-82a9-ef36ccfa9f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-yes-confirmmodal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-yes-confirmmodal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29b6833b-d5d5-468b-b32d-47c2a7890441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-yes-confirmmodal</value>
      <webElementGuid>d9b93462-9fd5-4395-b819-7e516a5fda65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator prieds-btn-primary mat-raised-button mat-button-base cdk-focused cdk-program-focused</value>
      <webElementGuid>8ab960d8-4c7e-4812-9772-941cb8d175e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>c07d7c6a-75f9-4edb-a7fb-9cc6f91b6f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-yes-confirmmodal&quot;)</value>
      <webElementGuid>3f00b6f2-6a82-4641-b1d1-2dcb9281c245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-yes-confirmmodal']</value>
      <webElementGuid>42787f4b-2fe0-421e-9355-476b09353110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-12']/app-confirm-modal/div/div/button[2]</value>
      <webElementGuid>3756c636-4f73-40f0-8b46-3cb2340d52c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[1]</value>
      <webElementGuid>acacff02-e42b-4cfb-95db-d8feca9fe20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure?'])[1]/following::button[2]</value>
      <webElementGuid>da844c54-40e1-4aff-8a94-09ff185fb9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support/Help'])[1]/preceding::button[1]</value>
      <webElementGuid>fed40fea-1a68-46d7-b9a3-133cb81d3558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-confirm-modal/div/div/button[2]</value>
      <webElementGuid>71543814-f396-4a55-a755-9bdf039adf9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-yes-confirmmodal' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>e2bc5a57-7f67-43c4-b3cd-be18ad921693</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
