<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mohon pilih salesman_code dahulu</name>
   <tag></tag>
   <elementGuidId>8ba9ec7d-aa30-4391-b9c7-7642a7a39e7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-message-snackbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-message-snackbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd990309-aed9-4c80-9a5d-49033235d1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-message-snackbar</value>
      <webElementGuid>8b7a5672-35ba-4280-93b5-89cffa375752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Mohon pilih salesman_code dahulu! </value>
      <webElementGuid>e2318aad-297b-4543-beb9-006c2df11833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-message-snackbar&quot;)</value>
      <webElementGuid>55d6e57a-6d58-46fb-b3a6-e72a85ea6717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='-message-snackbar']</value>
      <webElementGuid>86d41f04-c0f8-4207-a518-03a131590be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/snack-bar-container/app-snackbar/div/div[2]</value>
      <webElementGuid>fc69b1da-2ab0-443f-a353-5e6f1311344a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '-message-snackbar', '&quot;', ')')])[1]/following::div[6]</value>
      <webElementGuid>7531144c-8195-403f-a3ea-f035d285e6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[13]</value>
      <webElementGuid>5074fb3d-75e4-4c9a-81a3-ec8fbcc5082d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support/Help'])[1]/preceding::div[1]</value>
      <webElementGuid>907c8c21-65a2-4259-8bef-016793b8033c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::div[2]</value>
      <webElementGuid>c9661a15-b80d-4790-825d-989210d78a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mohon pilih salesman_code dahulu!']/parent::*</value>
      <webElementGuid>c9687e29-389d-4cbc-b7d4-a8ec145d2c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-snackbar/div/div[2]</value>
      <webElementGuid>e67e137f-1aa4-4acd-afc3-5fc4da7d23c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '-message-snackbar' and (text() = ' Mohon pilih salesman_code dahulu! ' or . = ' Mohon pilih salesman_code dahulu! ')]</value>
      <webElementGuid>1c8f97ba-6273-4ee6-94e9-e735011172b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
