<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mohon Isi Customer ID Terlebih Dahulu</name>
   <tag></tag>
   <elementGuidId>4d90858c-f512-4dad-a91b-5fa330443ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#-message-snackbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-message-snackbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e10a5439-ff7b-4b3b-a777-a7009ffd2fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-message-snackbar</value>
      <webElementGuid>32047316-c045-4ece-80d0-8ae62620b05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Mohon Isi Customer ID Terlebih Dahulu </value>
      <webElementGuid>9ef71817-d329-4972-bd64-51cb97ac0534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-message-snackbar&quot;)</value>
      <webElementGuid>eb8102c9-92d8-4d48-ad94-3fd7803143fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='-message-snackbar']</value>
      <webElementGuid>7b52f681-1845-4ebb-8ad1-346529dbd5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-11']/snack-bar-container/app-snackbar/div/div[2]</value>
      <webElementGuid>97a12f12-f519-4e1b-b913-ff7021cf905e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '-message-snackbar', '&quot;', ')')])[1]/following::div[6]</value>
      <webElementGuid>ad2f324c-da71-4255-8872-1ef1863c7579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[13]</value>
      <webElementGuid>901d053a-0d00-4aa7-bf77-e83f49aa6795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support/Help'])[1]/preceding::div[1]</value>
      <webElementGuid>2080b303-2a5b-4a12-bf9d-b24c02687e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::div[2]</value>
      <webElementGuid>5b856222-ae28-4bc7-8b86-84930b9bc677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mohon Isi Customer ID Terlebih Dahulu']/parent::*</value>
      <webElementGuid>f3e940b1-1c7e-48c0-855d-7e4f25cd8f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-snackbar/div/div[2]</value>
      <webElementGuid>97d66649-a1fa-440b-bfe1-01a405758032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '-message-snackbar' and (text() = ' Mohon Isi Customer ID Terlebih Dahulu ' or . = ' Mohon Isi Customer ID Terlebih Dahulu ')]</value>
      <webElementGuid>073573be-da4f-4af7-8bd2-58bfb16ea313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-10']/snack-bar-container/app-snackbar/div/div[2]</value>
      <webElementGuid>48f2dffe-d4d7-4c31-9d39-dd68695fdd3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[11]</value>
      <webElementGuid>2d201fab-0712-480a-a9ad-496cd30f2fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate ID'])[1]/following::div[13]</value>
      <webElementGuid>ab3ea1fe-de87-4a0f-ad76-5facc0bb13bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-12']/snack-bar-container/app-snackbar/div/div[2]</value>
      <webElementGuid>0da0ec64-9743-447a-9114-bcb641898c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/snack-bar-container/app-snackbar/div/div[2]</value>
      <webElementGuid>6332aa17-bb77-40b5-ac41-c438baa8c71b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
