<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hello,welcomeSign InIDUsernamePasswordv_1847fc</name>
   <tag></tag>
   <elementGuidId>25963936-d05b-44ca-a741-78443167fe5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.style-main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4dd5558f-2022-4b51-8335-5551f850f125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>65656cad-2789-412f-aa30-bddc8d1b9c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayoutalign</name>
      <type>Main</type>
      <value>center center</value>
      <webElementGuid>8ff5f993-b245-45b0-8a47-569908fec00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-main</value>
      <webElementGuid>f71c803d-f155-4808-892f-302a76c853f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hello,welcome!Sign InID/UsernamePasswordvisibility_offLoginVersion: 0.1.119Forgot password ?Need an Account? Sign Up</value>
      <webElementGuid>36009372-b821-4f8c-8242-3f9098ea2534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;style-main&quot;]</value>
      <webElementGuid>d53ab025-0750-4f2f-8514-f4b1243cb6e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>29948b32-4ab1-4444-8ee7-320b4fd4656e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hello,welcome!Sign InID/UsernamePasswordvisibility_offLoginVersion: 0.1.119Forgot password ?Need an Account? Sign Up' or . = 'Hello,welcome!Sign InID/UsernamePasswordvisibility_offLoginVersion: 0.1.119Forgot password ?Need an Account? Sign Up')]</value>
      <webElementGuid>c875b507-9a4c-485f-9355-4e1169018fb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
