<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hello,_style-people</name>
   <tag></tag>
   <elementGuidId>57435847-c86e-4668-a653-1953609fec64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.style-people</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dba6979b-a326-47e4-9b50-6741d00d9bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/img/login/prieds-people.png</value>
      <webElementGuid>6f712246-140f-4c9d-a463-85bed0372e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-people</value>
      <webElementGuid>cd9114cb-23d1-43ba-afd9-20343ed8464f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;style-main&quot;]/div[@class=&quot;style-smallphone&quot;]/div[1]/div[1]/img[@class=&quot;style-people&quot;]</value>
      <webElementGuid>4cf3872a-c55f-4aa9-b5a4-095a99a56d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2ea5c038-aa55-409a-b80b-647105a6e852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/img/login/prieds-people.png']</value>
      <webElementGuid>de44db59-8e45-47cb-bd76-ec170eaa6c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
