<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hello,_style-people</name>
   <tag></tag>
   <elementGuidId>57435847-c86e-4668-a653-1953609fec64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.style-people</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7e9c7466-45fa-42ff-b62a-25fd54552d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/img/login/prieds-people.png</value>
      <webElementGuid>79e5a0a6-c3ea-471d-a0d7-a24b21940256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-people</value>
      <webElementGuid>643b76c0-7aad-424c-aaef-4e9ca1857b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;style-main&quot;]/div[@class=&quot;style-smallphone&quot;]/div[1]/div[1]/img[@class=&quot;style-people&quot;]</value>
      <webElementGuid>a45ae043-9fab-465a-85a3-b3c259a07004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>32df1eaf-b60e-41c7-b0ca-b6b2e8da051a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/img/login/prieds-people.png']</value>
      <webElementGuid>14539d3b-dae6-4df1-bc39-e2031a01f3ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
