<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(id(, , -img-snackbar, , ))_-img-_6a7c1a</name>
   <tag></tag>
   <elementGuidId>29b2dfa8-0a99-4c63-b341-011f27dffe64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#-img-snackbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='-img-snackbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f0d84e9a-298a-484f-85ad-2603c4870550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>-img-snackbar</value>
      <webElementGuid>72e4430f-3bca-426d-ace6-1d28cf2bbf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/img/snackbar/BELUM-LENGKAP.png</value>
      <webElementGuid>90fbab2b-2d8e-40a7-b60b-f005aae7bf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>incomplete_input</value>
      <webElementGuid>ac20bce6-6d40-481d-9749-a482e067c1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;-img-snackbar&quot;)</value>
      <webElementGuid>cccb9abd-80a2-406e-9e78-0fb4fc1ad236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='-img-snackbar']</value>
      <webElementGuid>2dccd39b-153c-4c4f-97eb-3b333a953d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-10']/snack-bar-container/app-snackbar/div/div/img</value>
      <webElementGuid>5108a308-b700-4e80-8434-87fc96a90f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='incomplete_input']</value>
      <webElementGuid>5f8642a0-604f-494d-9880-6851aecce437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-snackbar/div/div/img</value>
      <webElementGuid>8c051387-0e3a-457e-b784-f6daa08e5e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '-img-snackbar' and @src = '/assets/img/snackbar/BELUM-LENGKAP.png' and @alt = 'incomplete_input']</value>
      <webElementGuid>5151b719-310c-4428-9ebf-cd078af17f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-12']/snack-bar-container/app-snackbar/div/div/img</value>
      <webElementGuid>dfc09814-6ccb-4cf4-af86-193af145d4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-11']/snack-bar-container/app-snackbar/div/div/img</value>
      <webElementGuid>7db08488-0325-4ea5-a163-cab7cbbdd2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-13']/snack-bar-container/app-snackbar/div/div/img</value>
      <webElementGuid>0d06e8e0-a661-43db-a878-760ae86cdf22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
