<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Region_createcustomer-customerregiste_b1824f</name>
   <tag></tag>
   <elementGuidId>0e8a3218-af5c-4c84-a0ea-860fd62db3df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createcustomer-customerregister-customermanagementinput-province-createcustomer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createcustomer-customerregister-customermanagementinput-province-createcustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32898aed-fd0b-4e26-8cb8-6e2a302709d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Province</value>
      <webElementGuid>51217814-a248-4641-8903-2eefc1d19773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-54 cdk-text-field-autofill-monitored ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>64addb92-b208-42b4-9255-1d0d278267d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createcustomer-customerregister-customermanagementinput-province-createcustomer</value>
      <webElementGuid>4c6ac84d-13ca-4cdf-b326-417a8b175330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1cf88abd-b0b4-4ba7-91da-b52de48ceeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>644d1af6-5d7b-4d37-bbc3-b61a21b1abd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementinput-province-createcustomer&quot;)</value>
      <webElementGuid>a1c62e98-8dec-4991-a1fc-d3bd938f4be9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createcustomer-customerregister-customermanagementinput-province-createcustomer']</value>
      <webElementGuid>bc2d1d45-beda-4de1-a9d6-af5194931e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-1']/div/app-create-customer/div/mat-card/mat-card-content/div[2]/div[2]/mat-form-field[5]/div/div/div[3]/input</value>
      <webElementGuid>cc63064d-f8b7-4321-9278-8e28416738fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field[5]/div/div/div[3]/input</value>
      <webElementGuid>bf12efd0-3bd4-4127-aab7-7d407a9495e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Province' and @id = 'createcustomer-customerregister-customermanagementinput-province-createcustomer']</value>
      <webElementGuid>b8f5bc63-dfbe-4be4-aad2-81880d981e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
