<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Salesman ID_createcustomer-customerre_2602e6</name>
   <tag></tag>
   <elementGuidId>e46d3784-8301-4142-9dcb-628bceddc871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createcustomer-customerregister-customermanagementinput-customername-createcustomer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createcustomer-customerregister-customermanagementinput-customername-createcustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3290b6a-6af2-41b7-84fb-3a0ae44e562f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Customer Name *</value>
      <webElementGuid>415f39bf-ca9d-484b-9db9-ee95fe1d3319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-44 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cad1e775-d139-44a8-862f-7cbc71a99de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createcustomer-customerregister-customermanagementinput-customername-createcustomer</value>
      <webElementGuid>2f6f66e3-b915-4425-9797-69c95de140f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ce65edc-6455-401b-aa14-b4d8999e1b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6da10b00-ddf4-4c44-9c64-f6af08680409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerName&quot;)/div[@class=&quot;mat-form-field-wrapper ng-tns-c165-44&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c165-44&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c165-44&quot;]/input[@id=&quot;createcustomer-customerregister-customermanagementinput-customername-createcustomer&quot;]</value>
      <webElementGuid>c9b80c07-2abe-4b38-84a4-e35fd2bcd9fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createcustomer-customerregister-customermanagementinput-customername-createcustomer']</value>
      <webElementGuid>e198aa62-fb57-4275-8eb8-5942498655b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-form-field[@id='CustomerName']/div/div/div[3]/input</value>
      <webElementGuid>698a43b7-ae5e-42d8-8a1c-a6fe50371bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>dd9490eb-cfb9-4239-bd4a-96f11f1f2247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Customer Name *' and @id = 'createcustomer-customerregister-customermanagementinput-customername-createcustomer']</value>
      <webElementGuid>2c54425c-2b3d-471b-933e-8f33fb72713a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
