<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_createcustomer-customerregister-_1096a9</name>
   <tag></tag>
   <elementGuidId>3012035f-752e-4326-bc8d-1eedcc3e0014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createcustomer-customerregister-customermanagementinput-remark-createcustomer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createcustomer-customerregister-customermanagementinput-remark-createcustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>234c7ec8-5407-4b63-8270-2159d6a27dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Remark</value>
      <webElementGuid>e12d4035-88b1-4074-97e4-3a85b49f0083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-46 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4ea1f3a7-4dac-4ecb-b4f4-96dfe750b152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createcustomer-customerregister-customermanagementinput-remark-createcustomer</value>
      <webElementGuid>df7a94be-d3c1-4c13-9724-906dc5063409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5322cff-557e-4429-9f8c-dc29b640fa7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef11278c-8ac8-4165-b66e-db37262fdf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c282-63 ng-trigger ng-trigger-translateTab&quot;]/app-create-customer[@class=&quot;ng-star-inserted&quot;]/div[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[2]/div[1]/mat-form-field[@class=&quot;mat-form-field fit-card ng-tns-c165-46 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label ng-untouched ng-pristine ng-valid mat-form-field-should-float mat-focused&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c165-46&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c165-46&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c165-46&quot;]/input[@id=&quot;createcustomer-customerregister-customermanagementinput-remark-createcustomer&quot;]</value>
      <webElementGuid>453debac-3b2e-4009-84be-b45f6de7f16b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createcustomer-customerregister-customermanagementinput-remark-createcustomer']</value>
      <webElementGuid>b3642671-49bc-4883-8d31-dd68fb51a46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-1']/div/app-create-customer/div/mat-card/mat-card-content/div[2]/div/mat-form-field[7]/div/div/div[3]/input</value>
      <webElementGuid>bfe69ad3-c652-49af-a85c-64b7914e0165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[7]/div/div/div[3]/input</value>
      <webElementGuid>73aeced2-6e27-4c31-8deb-9b1e71af55c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Remark' and @id = 'createcustomer-customerregister-customermanagementinput-remark-createcustomer']</value>
      <webElementGuid>33b11718-55a6-41ff-ad71-b47778406021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
