<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact No_createcustomer-customerreg_0f8d35</name>
   <tag></tag>
   <elementGuidId>bb9d2d4a-772a-4457-bdd7-655388bca08a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createcustomer-customerregister-customermanagementinput-region-createcustomer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createcustomer-customerregister-customermanagementinput-region-createcustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0042c2f0-6c63-4bbb-93cd-29109e10554d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Region</value>
      <webElementGuid>199cceff-76ff-4a5e-8407-5059a767953a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-50 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2e93122b-168b-4755-9c5b-d5c5ac6f0aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createcustomer-customerregister-customermanagementinput-region-createcustomer</value>
      <webElementGuid>a0220f55-15a7-4144-a259-799a611dc7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b9bfdbb4-0d60-4e83-b857-c55a6de4f993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3aea9cd9-4c32-4b33-8894-7c7cb5ac9cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementinput-region-createcustomer&quot;)</value>
      <webElementGuid>c0e35bf9-b636-462f-9959-7f68adcac2d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createcustomer-customerregister-customermanagementinput-region-createcustomer']</value>
      <webElementGuid>c42bb63f-8796-409f-9fd8-2b6c53e0f809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-1']/div/app-create-customer/div/mat-card/mat-card-content/div[2]/div[2]/mat-form-field[4]/div/div/div[3]/input</value>
      <webElementGuid>f49708a8-7ceb-41eb-a4a9-697f82a6d95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field[4]/div/div/div[3]/input</value>
      <webElementGuid>5e82c747-53b0-4e14-85e9-e716f0995a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Region' and @id = 'createcustomer-customerregister-customermanagementinput-region-createcustomer']</value>
      <webElementGuid>00a52497-b1d4-496c-84d1-094839488c31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
