<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_createcustomer-customerregister_6409b8</name>
   <tag></tag>
   <elementGuidId>d93aab4f-d063-4655-a117-5c5da4a37996</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createcustomer-customerregister-customermanagementinput-city-createcustomer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='createcustomer-customerregister-customermanagementinput-city-createcustomer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c1a6d4c-0496-4cf4-93c4-944d31ef2a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>City *</value>
      <webElementGuid>7977382a-3613-49e4-b144-3f07fa00fe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-47 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a0f7b5a9-bf96-4f0e-bdc4-b71fcaa4f383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>createcustomer-customerregister-customermanagementinput-city-createcustomer</value>
      <webElementGuid>9645c2db-01e7-4c0b-bcf4-6e9889187cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4e1c2679-16cb-42f8-bbf1-3e6c1e669440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f0afde2-2b4b-475c-b107-ce31c153c3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementinput-city-createcustomer&quot;)</value>
      <webElementGuid>bf523eab-520b-4e23-917f-3db845a837f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='createcustomer-customerregister-customermanagementinput-city-createcustomer']</value>
      <webElementGuid>e8bfec73-28e0-4211-921d-3421ff4dc234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-1']/div/app-create-customer/div/mat-card/mat-card-content/div[2]/div/mat-form-field[6]/div/div/div[3]/input</value>
      <webElementGuid>ec98a89a-9dd4-4418-a27e-7c8d4252259b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[6]/div/div/div[3]/input</value>
      <webElementGuid>bea09602-52e7-445e-a7cd-252d948d6066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'City *' and @id = 'createcustomer-customerregister-customermanagementinput-city-createcustomer']</value>
      <webElementGuid>4dc4b94d-7fe7-406b-b908-a50bee08485f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
