<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_FORGOT PASSWORD</name>
   <tag></tag>
   <elementGuidId>b9d089da-3df2-461f-9963-ef3a2e895a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-1']/forgot-password-modal/div/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.title-modal > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>65ee66f2-b48e-4e65-846f-13df23330e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FORGOT PASSWORD</value>
      <webElementGuid>2b3be0b4-581d-4e38-970a-f4ba7b5fa398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-1&quot;)/forgot-password-modal[@class=&quot;ng-star-inserted&quot;]/div[1]/div[1]/div[@class=&quot;title-modal&quot;]/label[1]</value>
      <webElementGuid>3e0ae7d0-dc57-4a0e-9b00-3e84c1531699</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-1']/forgot-password-modal/div/div/div/label</value>
      <webElementGuid>18dd14df-5358-41e6-b0d1-8efe4bfdc63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::label[1]</value>
      <webElementGuid>bdefa4ac-e12b-47b1-bab1-665e12804f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/preceding::label[1]</value>
      <webElementGuid>bc7cefdc-585c-42cd-af57-415fa047e713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::label[2]</value>
      <webElementGuid>cdf7bbd6-17a2-47f1-b727-81b118063706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FORGOT PASSWORD']/parent::*</value>
      <webElementGuid>172fc251-f74d-4ecc-a4b6-089f19f3eab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//forgot-password-modal/div/div/div/label</value>
      <webElementGuid>efc29a5c-114a-4ad4-b6d4-16961b85d2a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'FORGOT PASSWORD' or . = 'FORGOT PASSWORD')]</value>
      <webElementGuid>3664cdf7-2596-4cc6-860c-8e58ede67940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
