<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_more_vert</name>
   <tag></tag>
   <elementGuidId>ed509f7d-9c73-4cde-afae-c9d347b76fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0 > span.mat-button-wrapper > mat-icon.mat-icon.notranslate.material-icons.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0']/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>5240b7e2-60ae-4d57-a040-d86ff695b5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0c5654e0-43ca-47e3-8176-aa17ea5ad4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-no-color</value>
      <webElementGuid>2c13a3ce-a195-4d0f-b640-1b36c88ad4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41cffd6a-8e1f-4921-b5bc-1031f5b5ad9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>9e121f64-4c11-411b-bdec-069c7d1e4cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0&quot;)/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>2018d06c-a8cc-4bec-baf5-ce6666fc2c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0']/span/mat-icon</value>
      <webElementGuid>271980d1-51ab-412c-8064-87f26cfba7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data'])[2]/following::mat-icon[1]</value>
      <webElementGuid>58176c44-1519-4b8f-9e98-3c8254e7e691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET75'])[1]/following::mat-icon[1]</value>
      <webElementGuid>205cf0f6-bd71-48ec-9e56-0a576ba1c526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUS001'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>01613635-1b38-47fc-af83-ecdd14d6abbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CUS001TEST'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>7b32b4ea-2e9d-4b69-8b68-855dfa2e9250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_vert']/parent::*</value>
      <webElementGuid>4431bf64-81eb-4fbc-a898-b8d33f5c476e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/div/button/span/mat-icon</value>
      <webElementGuid>bd7d4dc1-694a-4415-a01f-95ec45755914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>5cd7541f-ae67-4b58-97aa-3f0f25019d52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
