<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>0ca01baa-7c48-49e2-a357-da5511f44b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-select-placeholder.ng-tns-c240-62.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='createcustomer-customerregister-customermanagementmatselect-termofpayment-createcustomer']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f05fdfa4-8451-43fe-9a6b-984506ac1375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-placeholder ng-tns-c240-62 ng-star-inserted</value>
      <webElementGuid>1625f842-3de6-4450-8625-38ac84cebd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>98c41cab-7efc-446c-a381-6206042dec26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementmatselect-termofpayment-createcustomer&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c240-62&quot;]/div[@class=&quot;mat-select-value ng-tns-c240-62&quot;]/span[@class=&quot;mat-select-placeholder ng-tns-c240-62 ng-star-inserted&quot;]</value>
      <webElementGuid>3afd8b53-43ea-4acd-85f0-a618da0c8714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='createcustomer-customerregister-customermanagementmatselect-termofpayment-createcustomer']/div/div/span</value>
      <webElementGuid>77016ec2-9a3d-4cb2-86a2-cd001078ac22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prefered Expedition'])[1]/following::span[1]</value>
      <webElementGuid>d02ee116-cf49-4e4c-95e7-f9ff9ea48f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::span[2]</value>
      <webElementGuid>df188aee-f865-4f22-b93c-518ef90add4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term Of Payment'])[1]/preceding::span[1]</value>
      <webElementGuid>29a6dfa0-5177-4df7-bc91-dc0b1e861da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term Of Payment Duration'])[1]/preceding::span[2]</value>
      <webElementGuid>b3aa832f-ceab-4eaa-9e33-58dd8bf3058a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[7]/div/div/div[3]/mat-select/div/div/span</value>
      <webElementGuid>0c7f481d-81db-4e62-8911-aef902cd9d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>bf6a6e23-f96e-4c85-a48c-4cc3025e2b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
