<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NET0</name>
   <tag></tag>
   <elementGuidId>04dd7ec4-a461-49f7-bd6b-adf734bc4552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='createcustomer-customerregister-customermanagementNET0matoption-termofpayment-createcustomer']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>edd78b47-8bfc-4d9e-8793-860359f8745e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>8bceb1c7-d7c5-488d-b870-11bd849870eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> NET0 </value>
      <webElementGuid>18d729fb-144a-42a1-a3ff-eefb33bc49d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementNET0matoption-termofpayment-createcustomer&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>494a6583-d886-403c-bbb2-fb9d5c4b45dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='createcustomer-customerregister-customermanagementNET0matoption-termofpayment-createcustomer']/span</value>
      <webElementGuid>0f61024f-2b41-4f68-a4a5-58f4d35181eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::span[1]</value>
      <webElementGuid>570e27f4-215f-4f61-bba9-addc19a64e99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate ID'])[1]/following::span[2]</value>
      <webElementGuid>e830f4b6-ac1f-4ede-aa7f-d45af6952afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET15'])[1]/preceding::span[1]</value>
      <webElementGuid>8ceb5cee-5360-4979-b5a3-9413b2264c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET30'])[1]/preceding::span[2]</value>
      <webElementGuid>2c916fea-7452-496f-b0b9-9c2bf8a7fa92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NET0']/parent::*</value>
      <webElementGuid>ace1db3b-3592-4310-9934-83f3af915861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option/span</value>
      <webElementGuid>63b49e34-2f5d-4484-8b7a-d1a5dc7aabd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' NET0 ' or . = ' NET0 ')]</value>
      <webElementGuid>5a717be7-374e-493b-92be-9ff4328b72d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
