<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ACCURATE</name>
   <tag></tag>
   <elementGuidId>36f384f6-b932-4fb1-a270-728aeddb254f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='createcustomer-customerregister-customermanagementACCURATEmatoption-salesmanid-createcustomer']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b3f26fe-8919-4306-bad4-cabe5323b79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>fed438af-2b7c-46a9-9834-cf71c825e2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> ACCURATE </value>
      <webElementGuid>66fbd0f7-ba0a-4ef5-bc0c-143332605725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementACCURATEmatoption-salesmanid-createcustomer&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>1c9ebd00-db06-4362-a320-52e9f47c12d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='createcustomer-customerregister-customermanagementACCURATEmatoption-salesmanid-createcustomer']/span</value>
      <webElementGuid>51d5f4db-4345-4cdd-9394-d6b1e2f0e4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::span[1]</value>
      <webElementGuid>02dcff02-cfe1-4ad6-81d3-11426f3ce804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generate ID'])[1]/following::span[2]</value>
      <webElementGuid>b7a14398-163e-47b2-b765-61a01bb47d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REYNER'])[1]/preceding::span[1]</value>
      <webElementGuid>b7f84ba6-73d0-49eb-9422-260c77a477e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support/Help'])[1]/preceding::span[2]</value>
      <webElementGuid>5b9fda8e-557b-4c1b-b958-eccfa7c49c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCURATE']/parent::*</value>
      <webElementGuid>2082e0e3-da01-441f-b435-85ecf9ce037f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option/span</value>
      <webElementGuid>5778cfaa-2649-40c1-acec-313a47984a14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ACCURATE ' or . = ' ACCURATE ')]</value>
      <webElementGuid>5a8ab6a9-cd67-49bd-b7f7-4d6c3c346bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
