<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Yes</name>
   <tag></tag>
   <elementGuidId>60cad864-5615-4423-a144-0bc186db7d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-yes-confirmmodal > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-yes-confirmmodal']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>23acde08-8126-4baa-a29f-6d8579e836e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>aa5bea30-4a4f-4420-ab61-d92946b8afbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>55e6bbb5-9c1b-497e-8ecd-7a23a0b26f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-yes-confirmmodal&quot;)/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>2e306bda-33f6-4ed2-bafe-3e7ee2b54f07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button-yes-confirmmodal']/span</value>
      <webElementGuid>cea4d853-a0e7-40c8-b2e7-5f36c529c7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::span[1]</value>
      <webElementGuid>5e0fd61b-23c5-4d99-8131-2c5ba5241bad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure?'])[1]/following::span[2]</value>
      <webElementGuid>6fcf0999-30eb-43b6-b9d3-6a64355b3ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support/Help'])[1]/preceding::span[1]</value>
      <webElementGuid>0fe800e5-73fb-492f-ac90-7a1570a78c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::span[1]</value>
      <webElementGuid>6d817daf-51c9-4795-97cf-0270843236e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Yes']/parent::*</value>
      <webElementGuid>3c5fda3a-dab1-4e65-bbe9-42d536797b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-confirm-modal/div/div/button[2]/span</value>
      <webElementGuid>1a2360d8-d05c-4105-964f-6640e687cebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>4177b046-5d61-4c62-99e6-10b41501217f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
