<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>0ca01baa-7c48-49e2-a357-da5511f44b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-select-placeholder.ng-tns-c240-65.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='createcustomer-customerregister-customermanagementmatselect-termofpayment-createcustomer']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>760fd037-1af1-4bd1-88a3-829de03bd7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-placeholder ng-tns-c240-65 ng-star-inserted</value>
      <webElementGuid>87bbcac0-3f54-4c34-8c7f-99aaf7f28e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>e5a07aca-e951-450d-97cb-44335ae0a6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementmatselect-termofpayment-createcustomer&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c240-65&quot;]/div[@class=&quot;mat-select-value ng-tns-c240-65&quot;]/span[@class=&quot;mat-select-placeholder ng-tns-c240-65 ng-star-inserted&quot;]</value>
      <webElementGuid>c1373e75-e018-4084-8155-8fedb8ebc37d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='createcustomer-customerregister-customermanagementmatselect-termofpayment-createcustomer']/div/div/span</value>
      <webElementGuid>1c5cc93d-3a19-416b-8b20-26ff7994dcab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prefered Expedition'])[1]/following::span[1]</value>
      <webElementGuid>e9f3c33e-fbdd-40d6-a51c-1285b4daeadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::span[2]</value>
      <webElementGuid>7e2516b2-6b15-4469-8baf-345e7a529abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term Of Payment'])[1]/preceding::span[1]</value>
      <webElementGuid>ff88ee00-5964-4047-92ec-6602803e4034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term Of Payment Duration'])[1]/preceding::span[2]</value>
      <webElementGuid>b8b5da8d-331b-4cd1-b8bc-06c40c978851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[7]/div/div/div[3]/mat-select/div/div/span</value>
      <webElementGuid>923ee76f-f4d3-42cd-b5f7-2562a9e849aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' ' or . = ' ')]</value>
      <webElementGuid>8adfc99a-d443-4c8c-845e-88e98367e72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
