<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NET75</name>
   <tag></tag>
   <elementGuidId>0ab7c764-ffea-49fc-868c-9a58a4c10f51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#createcustomer-customerregister-customermanagementNET75matoption-termofpayment-createcustomer > span.mat-option-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='createcustomer-customerregister-customermanagementNET75matoption-termofpayment-createcustomer']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dbf568cb-596b-49b3-88ef-97d643add831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>52c2eec1-c1cf-4a6f-b483-164babc77567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> NET75 </value>
      <webElementGuid>3855d482-f0f0-437a-be78-322378a620e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;createcustomer-customerregister-customermanagementNET75matoption-termofpayment-createcustomer&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>0c69731d-9df3-4b17-b2df-666de5aaa5f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='createcustomer-customerregister-customermanagementNET75matoption-termofpayment-createcustomer']/span</value>
      <webElementGuid>bc327060-cc9e-4ed6-870a-c113e596507d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET60'])[1]/following::span[1]</value>
      <webElementGuid>f220184d-bcb4-4c25-a9a6-1bbd15028bdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET45'])[1]/following::span[2]</value>
      <webElementGuid>dede0dba-4d4d-4bb0-af9b-a742e9dfc74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET90'])[1]/preceding::span[1]</value>
      <webElementGuid>eecb1ba3-bc7a-4129-b53e-1794daf131db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom'])[1]/preceding::span[2]</value>
      <webElementGuid>1d88e098-9fd9-4e96-ad66-9d94313ac7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NET75']/parent::*</value>
      <webElementGuid>bf89004a-c219-4abd-a1b2-eb692f2eb53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[6]/span</value>
      <webElementGuid>d9c9146a-d2db-405f-b214-b18aa34f2aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' NET75 ' or . = ' NET75 ')]</value>
      <webElementGuid>1e34d2d7-cdc9-4b9b-b782-fe9b210bc1ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
