<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>44e021c8-c213-4552-927a-d99e99be2da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-editcustostomermodel-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-editcustostomermodel-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46638d19-1743-43c3-bc3f-84f484864a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-editcustostomermodel-customermanagement</value>
      <webElementGuid>e80dbdb7-4758-4fb4-a346-d5b66076e4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>prieds</value>
      <webElementGuid>04ae9b4b-3d58-48b4-91eb-a903e46a811b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-raised-button mat-button-base mat-prieds cdk-focused cdk-mouse-focused</value>
      <webElementGuid>650ce816-5312-487e-8115-72896c53e5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save </value>
      <webElementGuid>baef9efb-476e-4484-bb4f-fc6293e81174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-editcustostomermodel-customermanagement&quot;)</value>
      <webElementGuid>b114c5bf-162b-4276-9e21-fcc52955d942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-editcustostomermodel-customermanagement']</value>
      <webElementGuid>17d93152-4ee7-4476-9356-3460bee27b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-6']/details-edit-customer-management-modal/div/mat-dialog-actions/button</value>
      <webElementGuid>c5daa06c-2d4b-4db9-a01a-50f4c2632e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Max file size 3Mb. Please upload file with example .jpg .jpeg .png and .pdf format'])[1]/following::button[1]</value>
      <webElementGuid>25dcf46f-1fb8-44ce-af71-066c0d96842f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tier'])[1]/following::button[3]</value>
      <webElementGuid>ccffdd21-6787-43c9-8835-f126f39c620c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>e5c08234-7b4e-4438-9431-eefba60ca904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/button</value>
      <webElementGuid>1c87b6bf-4a1d-42d5-9dac-252e5e11b717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-editcustostomermodel-customermanagement' and (text() = ' Save ' or . = ' Save ')]</value>
      <webElementGuid>6f74a6d5-6fc2-4274-8742-6aa3585896c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
