<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Yes</name>
   <tag></tag>
   <elementGuidId>c0a157b6-021c-4964-b512-c1e2ed0ccf6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-yes-confirmmodal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-yes-confirmmodal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba0a8a4c-827c-487d-a7e1-93b8a3591bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-yes-confirmmodal</value>
      <webElementGuid>f2cafc67-b60c-47d8-a7f7-c64f360ed2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator prieds-btn-primary mat-raised-button mat-button-base cdk-focused cdk-program-focused</value>
      <webElementGuid>bfa4f381-a176-4292-a2d6-7eb2efb191bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>5d1c88a3-9acc-464a-861b-9d930e92260e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-yes-confirmmodal&quot;)</value>
      <webElementGuid>38e54f54-ad30-4863-b566-939cf2b3b6bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-yes-confirmmodal']</value>
      <webElementGuid>abaed8e7-8088-433a-9d8e-958c73eaeb20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-8']/app-confirm-modal/div/div/button[2]</value>
      <webElementGuid>ff49229a-8ba4-4936-8f77-a21fcd3a843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::button[1]</value>
      <webElementGuid>7eda9736-8540-4287-a631-9c24a211deab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure?'])[1]/following::button[2]</value>
      <webElementGuid>852fc244-aa7b-4b2c-be3d-11a66ae5d403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support/Help'])[1]/preceding::button[1]</value>
      <webElementGuid>561310a7-d204-4592-900e-98c08b8caedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-confirm-modal/div/div/button[2]</value>
      <webElementGuid>7b604f32-207c-4756-bcc9-a098d4ea4295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-yes-confirmmodal' and (text() = 'Yes' or . = 'Yes')]</value>
      <webElementGuid>761ffbd9-5faf-44be-a8a7-804e1ce4e732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
