<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NET75</name>
   <tag></tag>
   <elementGuidId>50223d22-c560-4eac-9a9b-0c1cf3884d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-value.ng-tns-c240-127</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='matselect-edittermofpayment-customermanagement']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ccacab1-fce9-40fc-84eb-28e5a4e3ff04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c240-127</value>
      <webElementGuid>7fce97db-dec0-4366-a20b-1ba8d81f9e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NET75</value>
      <webElementGuid>ed40f61d-aaa2-4450-8287-f1227db82b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matselect-edittermofpayment-customermanagement&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c240-127&quot;]/div[@class=&quot;mat-select-value ng-tns-c240-127&quot;]</value>
      <webElementGuid>99788c19-3f7a-466e-bea6-2844faf31ae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='matselect-edittermofpayment-customermanagement']/div/div</value>
      <webElementGuid>a16ba373-2593-4957-b14b-b2833b4417e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prefered Expedition'])[1]/following::div[16]</value>
      <webElementGuid>3a44ddd4-818f-42ea-a621-76d9f2f50dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Province'])[1]/following::div[30]</value>
      <webElementGuid>ddef7030-81c9-4209-951c-cd3276a138d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term Of Payment'])[2]/preceding::div[3]</value>
      <webElementGuid>76b37f19-bfab-450b-afd0-a62b768aa901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[5]/div/div/div[3]/mat-select/div/div</value>
      <webElementGuid>55e63c29-e849-4f72-b948-c3ab14b5422e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'NET75' or . = 'NET75')]</value>
      <webElementGuid>039ce3b2-c013-4935-b8cc-f1dbfef1688d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
