<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hello,_style-people</name>
   <tag></tag>
   <elementGuidId>e83f06d9-ca88-4f67-8e25-5ea99412cdcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.style-people</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>66179156-e405-4b49-a1a7-a0a087cff436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../assets/img/login/prieds-people.png</value>
      <webElementGuid>96da5ee6-fa48-471b-bd79-320e3b49fd7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-people</value>
      <webElementGuid>2bdd65bf-93c7-489e-9fdd-b3a07590889b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;style-main&quot;]/div[@class=&quot;style-smallphone&quot;]/div[1]/div[1]/img[@class=&quot;style-people&quot;]</value>
      <webElementGuid>f4eb24c3-18d2-4e64-8027-ed72b45f16fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ccf34b32-184e-4323-8eb4-7f741c20434f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../assets/img/login/prieds-people.png']</value>
      <webElementGuid>07bea95a-ded8-4fa5-b215-970db2a97660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
