<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact No_input-editcontactnno-custo_2aebb7</name>
   <tag></tag>
   <elementGuidId>fbd67667-fa75-4cfc-997f-d3b1b56d36fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c165-117 > #input-editcontactnno-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='input-editcontactnno-customermanagement'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>481406d6-cb6d-4b2a-ac08-1eb979839fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-editcontactnno-customermanagement</value>
      <webElementGuid>ef4cc891-e55e-4a90-ba6b-3e272d9b2b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>PIC</value>
      <webElementGuid>c78c4ed3-9719-45ea-b298-5c5f257010c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>pic</value>
      <webElementGuid>aef57593-a4a5-4a3b-9236-7dd023a0d8ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-117 cdk-text-field-autofill-monitored ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>9b0f8d02-c41a-43e7-9600-29a0c2c91111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d809c918-94cd-4279-b0a0-f6f8b67ab230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3da5bc23-d635-4751-9862-a44da2b6885e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-6&quot;)/details-edit-customer-management-modal[@class=&quot;ng-star-inserted&quot;]/div[1]/mat-dialog-content[@class=&quot;mat-dialog-content&quot;]/div[@class=&quot;ng-valid ng-dirty ng-touched&quot;]/mat-form-field[@class=&quot;mat-form-field ng-tns-c165-117 mat-primary mat-form-field-type-mat-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-should-float mat-form-field-has-label ng-untouched ng-valid mat-focused ng-dirty&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c165-117&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c165-117&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c165-117&quot;]/input[@id=&quot;input-editcontactnno-customermanagement&quot;]</value>
      <webElementGuid>1ed748fe-e346-4849-82a9-f415fd116e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='input-editcontactnno-customermanagement'])[2]</value>
      <webElementGuid>dc4f3995-72e0-4d6c-8da8-00763f0cd3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-6']/details-edit-customer-management-modal/div/mat-dialog-content/div/mat-form-field[5]/div/div/div[3]/input</value>
      <webElementGuid>ec715b6e-510b-4dcf-a9fd-5ecbe3454a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[5]/div/div/div[3]/input</value>
      <webElementGuid>db7afa80-1c84-4d03-83af-f598a35e51a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-editcontactnno-customermanagement' and @placeholder = 'PIC']</value>
      <webElementGuid>dea389ba-adc5-4d4d-80b8-8398f30d6b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
