<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_input-editregion-customermanagement</name>
   <tag></tag>
   <elementGuidId>2a116dde-43dc-408f-8d0b-c1113d1b293d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-editregion-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-editregion-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0eb8856-2c14-4d1d-bc67-5220c2cfc352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-editregion-customermanagement</value>
      <webElementGuid>d4327703-6513-4b0a-a4d9-bf4d32dc6711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>9944684e-030c-48a5-a524-996dd38a6a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-123 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0ba2ead8-654b-4880-ba3d-1033e973ad53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c0534b0c-a8e0-442f-a875-001c0f71b6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d1d66b9-e1f6-4a7d-8585-4a129214f014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-editregion-customermanagement&quot;)</value>
      <webElementGuid>86d4b1a3-8340-4a1f-b2ce-866a394ce55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-editregion-customermanagement']</value>
      <webElementGuid>60c6b077-823e-4c7c-9ef3-3aa4035f5ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-6']/details-edit-customer-management-modal/div/mat-dialog-content/div[2]/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>1084de13-7f01-4ef7-8e40-8f6ea2559752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field[2]/div/div/div[3]/input</value>
      <webElementGuid>33d06c22-3d35-411e-9447-1ae6ff495d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-editregion-customermanagement']</value>
      <webElementGuid>9eb01f83-5268-4af3-9773-7c0bf57fd54c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
