<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Region_input-editprovince-customermanagement</name>
   <tag></tag>
   <elementGuidId>37341821-8292-4385-b3ca-097992883df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-editprovince-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-editprovince-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac2358ad-6463-49c9-aa2b-3f2298c31317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-editprovince-customermanagement</value>
      <webElementGuid>e26c87d9-eea8-4fe4-9195-b83b830881f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>province</value>
      <webElementGuid>ca162953-6a57-4470-a22d-c408483bcecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-124 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>9145fade-e5dc-4451-a303-d953aa7cc62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>71b3ff62-ea47-4f46-9ec5-dd908725254e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5c204c6-a683-4c5d-babe-ffb0939f5f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-editprovince-customermanagement&quot;)</value>
      <webElementGuid>69d05a34-7157-4c85-a626-359a1d7b4bc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-editprovince-customermanagement']</value>
      <webElementGuid>ec2239cc-e926-4415-80ed-0854a37168ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-6']/details-edit-customer-management-modal/div/mat-dialog-content/div[2]/mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>a5317d9f-22d4-447c-ba9b-436627480a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[3]/div/div/div[3]/input</value>
      <webElementGuid>06fb3317-a3a6-4f3a-9f61-0c552749324e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-editprovince-customermanagement']</value>
      <webElementGuid>06eb400a-093f-44c3-967a-42b7d26a1fdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
