<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Term Of Payment_input-edittermofpayme_fc94da</name>
   <tag></tag>
   <elementGuidId>904d034d-f191-4425-b7bc-4b4d93b583a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-edittermofpaymentduration-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-edittermofpaymentduration-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60b2b3b9-2646-47bd-86cc-50f20dbd08a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-edittermofpaymentduration-customermanagement</value>
      <webElementGuid>8980754b-9caf-4955-992f-7d4212462e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7b563b3f-f531-46e9-93fe-d6277df6569d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Term Of Payment Duration</value>
      <webElementGuid>5c7bc28f-59a1-429c-aef7-9ef2f4b6dc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-128 cdk-text-field-autofill-monitored ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>09fb8763-fdff-4d70-be78-469068885e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3accad22-fc7f-4716-bcf6-6ed55504634b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6cf904c5-a3d0-4304-a690-ec170886a813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-edittermofpaymentduration-customermanagement&quot;)</value>
      <webElementGuid>0f493266-f209-4915-99cf-b7366db4fbfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-edittermofpaymentduration-customermanagement']</value>
      <webElementGuid>8859da85-218e-4c50-9671-2e20f5db14b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-6']/details-edit-customer-management-modal/div/mat-dialog-content/div[2]/mat-form-field[6]/div/div/div[3]/input</value>
      <webElementGuid>7575d09f-b70d-4ac6-af66-e4c59aeae51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field[6]/div/div/div[3]/input</value>
      <webElementGuid>8de18e80-b6bc-44a4-9637-40a0ac7f0b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-edittermofpaymentduration-customermanagement' and @type = 'number' and @placeholder = 'Term Of Payment Duration']</value>
      <webElementGuid>8cfc5fd2-14d0-496d-8f23-eac23ba1b12c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
