<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_more_vert</name>
   <tag></tag>
   <elementGuidId>70aadf3a-caee-4f98-bfaa-96f0f25fc15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0 > span.mat-button-wrapper > mat-icon.mat-icon.notranslate.material-icons.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0']/span/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>2699f634-53c9-4440-8dbe-759dc69bec49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb63461e-0f30-40b3-99fe-140c3471dc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate material-icons mat-icon-no-color</value>
      <webElementGuid>434d4f57-73c6-4cd9-b3e4-e1c5eeb4fee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>374f4749-7be5-4b52-bd59-2265f8a1c7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>5a8a3c2d-acd8-44e2-a7b4-2a3b94bd6aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0&quot;)/span[@class=&quot;mat-button-wrapper&quot;]/mat-icon[@class=&quot;mat-icon notranslate material-icons mat-icon-no-color&quot;]</value>
      <webElementGuid>8a5bada6-7483-404f-802c-59113fde5009</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='matmenu-tablecustomerlist-columnactions-action-customerlist-customermanagement-0']/span/mat-icon</value>
      <webElementGuid>4534bedb-dd9e-4c26-b6fa-7777e865714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REYNER-Customer...png'])[1]/following::mat-icon[1]</value>
      <webElementGuid>63c68f2b-72ae-4f8e-89da-de4955cf077d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET75'])[1]/following::mat-icon[1]</value>
      <webElementGuid>a5758614-a794-4769-9cab-0f205ffed74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REYNER-Customer-UMKM21484-Sleman'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>1f860ec3-aa81-4c48-98c4-58b68e010d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer-UMKM21484'])[1]/preceding::mat-icon[1]</value>
      <webElementGuid>d035503a-873a-4164-91aa-76d20330ee56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='more_vert']/parent::*</value>
      <webElementGuid>9a147893-fb9b-4129-8b7d-b9cfd828fca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/div/button/span/mat-icon</value>
      <webElementGuid>b32d3cb7-5182-4fa0-b84e-5f8de0f8d79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-icon[(text() = 'more_vert' or . = 'more_vert')]</value>
      <webElementGuid>963cf590-8887-4795-af56-18b8396e7bb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
