<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Address_input-editaddress2-custome_2f951e</name>
   <tag></tag>
   <elementGuidId>97cb2020-382a-44b0-bf92-ca808fb2d326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-editaddress2-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-editaddress2-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8058da12-4f56-4fee-ad44-dc22d34cf68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-editaddress2-customermanagement</value>
      <webElementGuid>e926069a-e72c-4db7-9716-a2bc57022dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address 2</value>
      <webElementGuid>9372e548-acc4-4a8c-9828-32d266cf982a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>address_2</value>
      <webElementGuid>b043c27e-728d-42c3-9cb2-cc625eba6544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-121 cdk-text-field-autofill-monitored ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>c6f4fc90-fd9c-4e34-b82b-78e01ebb1258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e6c52f6-94ca-4038-b691-ceb15a184332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>44fe954f-7209-4491-96ad-82c7aab3ca32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-editaddress2-customermanagement&quot;)</value>
      <webElementGuid>89a2deff-ae89-4a84-b1e8-6e6da743daf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-editaddress2-customermanagement']</value>
      <webElementGuid>926607d7-9b9a-4678-b987-c1d2a578933f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-6']/details-edit-customer-management-modal/div/mat-dialog-content/div/mat-form-field[9]/div/div/div[3]/textarea</value>
      <webElementGuid>fdd9865e-2420-4550-81d7-ed264793e8cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[9]/div/div/div[3]/textarea</value>
      <webElementGuid>0bf185c7-a10f-4a89-8764-b644c8100d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-editaddress2-customermanagement' and @placeholder = 'Address 2']</value>
      <webElementGuid>9c86bbaa-8090-4bfc-bd35-02e082bb9216</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
