<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>b18deb89-2cc7-4247-b76b-2c1ce6b88933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#matmenu-tablecustomerlist-columnactions-action-edit-customerlist-customermanagement-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='matmenu-tablecustomerlist-columnactions-action-edit-customerlist-customermanagement-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a454446-06dc-4aa2-8501-6025743ee979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator prieds-matMenu-button mat-menu-item ng-tns-c237-118 cdk-focused cdk-mouse-focused</value>
      <webElementGuid>457120ef-5123-43bb-bcaf-aebc47cec167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>matmenu-tablecustomerlist-columnactions-action-edit-customerlist-customermanagement-0</value>
      <webElementGuid>7b718ed7-4f75-4932-8c5c-8ded688e2a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>99cb3d7a-19c0-4fd5-9b68-50583880e388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>360b1b5e-64a3-4434-abc9-6c5762b8fa4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>564cfea7-1964-45f1-9bb6-377d8934ee41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Edit </value>
      <webElementGuid>5474adfc-5b89-44aa-a785-a3dc64121a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matmenu-tablecustomerlist-columnactions-action-edit-customerlist-customermanagement-0&quot;)</value>
      <webElementGuid>386948c7-1c98-481d-943f-06feeb7a267d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='matmenu-tablecustomerlist-columnactions-action-edit-customerlist-customermanagement-0']</value>
      <webElementGuid>46444d6d-ebb4-4e58-9499-3b6b1877ce77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-74']/div/button</value>
      <webElementGuid>8c7dd2cc-f590-4e73-b834-a676cfdf298a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data'])[2]/following::button[2]</value>
      <webElementGuid>220cc4a6-f511-4ff4-a425-35d71a3f73f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET15'])[1]/following::button[2]</value>
      <webElementGuid>5ba7ca39-9d74-4c20-9491-a01cdf9b6cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support/Help'])[1]/preceding::button[1]</value>
      <webElementGuid>d7a997ee-9ca4-4dba-b04e-b76e7bc62f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::button[1]</value>
      <webElementGuid>abae0cd2-d6a3-46a6-8cda-90317d889d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>4a209426-53ac-43a9-90ae-c23249f1481d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/button</value>
      <webElementGuid>0643bc30-e637-4425-a25d-cf2fa128244f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'matmenu-tablecustomerlist-columnactions-action-edit-customerlist-customermanagement-0' and (text() = ' Edit ' or . = ' Edit ')]</value>
      <webElementGuid>10fb09a8-f8b0-46ab-875b-41dc7380acd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
