<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Master</name>
   <tag></tag>
   <elementGuidId>35d563e5-d932-4574-a30b-773b4aeac560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Master > span.mat-button-wrapper > div > div.menu-title-transition > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Master']/span/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>29f93b7d-f2a1-44ce-8284-ff22639e9544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Master </value>
      <webElementGuid>da9e4040-06ff-47f8-b60a-ba84338d3c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Master&quot;)/span[@class=&quot;mat-button-wrapper&quot;]/div[1]/div[@class=&quot;menu-title-transition&quot;]/div[1]</value>
      <webElementGuid>6931b69b-6971-4fd2-8fcc-6bece69f431d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='Master']/span/div/div/div</value>
      <webElementGuid>766dc0b7-342d-478e-a770-5616293320dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warehouse'])[1]/following::div[5]</value>
      <webElementGuid>75d0ed89-4d09-4876-85b1-cf721a00772a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::div[10]</value>
      <webElementGuid>270dd286-f605-4fc7-86b9-3ce13fe94390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchasing'])[1]/preceding::div[4]</value>
      <webElementGuid>0c9e6082-1eea-4d63-b105-b2c1384ff3af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[1]/preceding::div[9]</value>
      <webElementGuid>69774adf-fdf7-48b3-b3b5-970616bceffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Master']/parent::*</value>
      <webElementGuid>11d41cf0-1f12-407b-99b1-cad3f9eb18c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-menu-element[3]/button/span/div/div/div</value>
      <webElementGuid>d0da96e2-2f98-430b-83c9-63c057ac3c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Master ' or . = ' Master ')]</value>
      <webElementGuid>1c8e9f73-9fbf-4e61-ba6d-7d8e4bea8748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
