<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Register Import_input-custom_9d3571</name>
   <tag></tag>
   <elementGuidId>3ecfc904-4d65-48ff-8bd3-d329db2dbd9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-customerid-customerlist-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-customerid-customerlist-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e65391f3-9dd5-4be3-aed4-370a3634cb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-customerid-customerlist-customermanagement</value>
      <webElementGuid>2ab35940-a1d7-4b4e-aaa4-6f6baacb3d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c165-38 cdk-text-field-autofill-monitored ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>60025f36-a667-42a5-8af5-0f4aec692534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f862467b-a8f0-46ad-ae09-81fc01e6b921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>24b730ae-a54b-4476-9a06-ea19a3e94248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-customerid-customerlist-customermanagement&quot;)</value>
      <webElementGuid>01510b2f-ca01-4fb8-abba-2d57c2c2d46c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-customerid-customerlist-customermanagement']</value>
      <webElementGuid>0d3c66b8-ed9c-42a5-b74f-fa33e07497e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/div/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>030951d1-5a6f-44c8-b6c2-563c08b2e6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>520f048b-4e9f-41f1-b3e0-35b2ac77e7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-customerid-customerlist-customermanagement']</value>
      <webElementGuid>ae7e8498-355d-49a6-95c2-f682530fd370</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
