<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Search</name>
   <tag></tag>
   <elementGuidId>cccaaaef-6e5c-4d0d-93ed-7d2300f77a5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button-search-customerlist-customermanagement > span.mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-search-customerlist-customermanagement']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>85543f1d-c23d-4ee6-9485-07152504931e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>2c23f5c8-5a79-489e-beb3-17f205486486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search </value>
      <webElementGuid>d06714fd-b607-4c08-8360-951fc357f615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-search-customerlist-customermanagement&quot;)/span[@class=&quot;mat-button-wrapper&quot;]</value>
      <webElementGuid>bb9e46d5-8857-40c5-b4fc-c85722a408be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='button-search-customerlist-customermanagement']/span</value>
      <webElementGuid>76baccd0-d032-4be4-bcc2-fcc52ea54bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[1]/following::span[2]</value>
      <webElementGuid>2ea3bdc4-44e4-4738-b510-9ea6be8a425f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer ID'])[1]/following::span[4]</value>
      <webElementGuid>2c3d4ac6-06fd-46bc-9a66-4c110d9df674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/preceding::span[2]</value>
      <webElementGuid>44e4d194-4b00-4e4e-a065-1194b5f1c0b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search']/parent::*</value>
      <webElementGuid>0b1b0083-d7b9-403e-a0aa-83a292579c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card/div/div/button/span</value>
      <webElementGuid>cfbba7b5-358d-4f81-a789-949d3f3e596d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Search ' or . = ' Search ')]</value>
      <webElementGuid>d9ba7bbc-8e6a-464b-abe6-b31fd8f3f866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
