<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download  expand_more</name>
   <tag></tag>
   <elementGuidId>d98a5104-37da-48a9-89c5-c72e740ef4d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#matmenu-download-customerlist-customermanagement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='matmenu-download-customerlist-customermanagement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c6b9c44d-08bd-466e-999b-55c34a81ed80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61c19e2b-96b4-483e-915e-4332162df9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>matmenu-download-customerlist-customermanagement</value>
      <webElementGuid>1aa7180f-f738-4e28-bd14-3dc78ae37198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger btn-download btn-download-custom mat-stroked-button mat-button-base</value>
      <webElementGuid>8c162530-1991-4ca1-8be9-0b750ce820e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Download  expand_more </value>
      <webElementGuid>cca847b5-ef4c-43b2-85de-8023ba7489ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matmenu-download-customerlist-customermanagement&quot;)</value>
      <webElementGuid>626da80f-085f-4423-b442-5d68947b31d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='matmenu-download-customerlist-customermanagement']</value>
      <webElementGuid>ec08a677-b4af-4522-9926-f4ae2a0f9bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/mat-card/div/div[2]/button</value>
      <webElementGuid>e6ba7ee9-7e46-491c-85ce-a82a6309260d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::button[1]</value>
      <webElementGuid>4c90e6ff-84b6-4f13-8406-a6de00c8499d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[1]/following::button[2]</value>
      <webElementGuid>e6664f8d-958f-49cd-9245-18ce48dd03b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/preceding::button[1]</value>
      <webElementGuid>51204a3b-539b-4d83-ab38-d7747d4581f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card/div/div[2]/button</value>
      <webElementGuid>41803ab0-dde7-4116-b615-f0dc3b325041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'matmenu-download-customerlist-customermanagement' and (text() = ' Download  expand_more ' or . = ' Download  expand_more ')]</value>
      <webElementGuid>35c6f56d-5726-48a2-bb63-9793970c6066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
