<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Customer List</name>
   <tag></tag>
   <elementGuidId>395e7bdf-2fd6-4bf0-a600-3edfe01068db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-tab-label-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-tab-label-0-0']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>440eeca9-75f6-4dc9-b956-9e58bf18a419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-tab-label-content</value>
      <webElementGuid>1050d424-e3b4-4431-8161-75a1bd50c21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer List</value>
      <webElementGuid>bb879c0e-14e4-46a4-8882-a82deaffbafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-label-0-0&quot;)/div[@class=&quot;mat-tab-label-content&quot;]</value>
      <webElementGuid>7e5c00a0-2935-4d3a-9301-81709572c448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-tab-label-0-0']/div</value>
      <webElementGuid>c586769f-e18d-4e4f-a731-49a02dc1a1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Management'])[1]/following::div[13]</value>
      <webElementGuid>a07626ff-8408-496b-9309-b162fa58ff35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Register'])[1]/preceding::div[1]</value>
      <webElementGuid>8cb126ea-f53b-4179-8353-d1e5d93b0e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Register Import'])[1]/preceding::div[3]</value>
      <webElementGuid>0980da95-bdeb-4259-b32e-e7e6200856ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer List']/parent::*</value>
      <webElementGuid>b7926a29-dbed-442b-a968-c32009fb691d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-tab-header/div[2]/div/div/div/div</value>
      <webElementGuid>d22ca764-83a9-47f7-a5f0-1ef47edf6da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Customer List' or . = 'Customer List')]</value>
      <webElementGuid>6b52aeb5-18ff-41b1-8205-203bc603d7dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
