<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Customer-UMKM73905updatedPF7OT90</name>
   <tag></tag>
   <elementGuidId>7d6a0ad8-863d-4f71-9ffc-0d8106ac45ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.mat-cell.cdk-cell.cdk-column-name.mat-column-name.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-customelist-customermanagement']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cedbaa34-f38e-4e8f-9de2-aeb03b0033d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f772b235-e28e-4e52-9a25-279a22e8573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell cdk-column-name mat-column-name ng-star-inserted</value>
      <webElementGuid>9e721259-e7ee-469a-9cdd-a4d256907e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Customer-UMKM73905updatedPF7OT90 </value>
      <webElementGuid>24a9d025-02b8-43bb-a73b-d28bfc798d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-customelist-customermanagement&quot;)/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell cdk-column-name mat-column-name ng-star-inserted&quot;]</value>
      <webElementGuid>efb515ef-d077-4593-bbfc-d84aa659e64d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-customelist-customermanagement']/tbody/tr/td[2]</value>
      <webElementGuid>d087ad73-0b81-449f-bda6-85193f015f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REYNER-Customer-UMKM73905-Sleman'])[1]/following::td[1]</value>
      <webElementGuid>faa6fa34-d56f-44d4-a521-5b764f35d338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::td[2]</value>
      <webElementGuid>b364a36c-08a9-4719-a468-fb8faad7fcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UMKMupdatedNPjCH'])[1]/preceding::td[1]</value>
      <webElementGuid>16744fc5-2cf9-4505-ae71-914032706fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='umkm@mailinator.com'])[1]/preceding::td[2]</value>
      <webElementGuid>b3f0c402-2d39-4ee3-901f-455247603146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer-UMKM73905updatedPF7OT90']/parent::*</value>
      <webElementGuid>2a714fae-294a-4a9a-8421-e4ff367b393b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>32ba3616-2ffe-4aca-b51a-f810cb9a452c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Customer-UMKM73905updatedPF7OT90 ' or . = ' Customer-UMKM73905updatedPF7OT90 ')]</value>
      <webElementGuid>d0fa6048-73e4-4a47-b673-4991a2f7b36e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
